version: "3.3"

services: 
  front-aliviate:
    restart: always 
    build: .
    ports:
      - "4000:3000"
    networks:
      - webnet
    volumes:
      - ./src:/app/src

networks:
  webnet:
    driver: bridge
    ipam: 
      driver: default